apiVersion: v1
kind: Service
metadata:
  name: ecuacion
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30003
  selector:
    app: ecuacion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecuacion
spec:
  selector:
    matchLabels:
      app: ecuacion
  template:
    metadata:
      labels:
        app: ecuacion
    spec:
      containers:
        - name: ecuacion
          image: ecuacion:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
