apiVersion: v1
kind: Service
metadata:
  name: resta
spec:
  ports:
    - port: 8000
  selector:
    app: resta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resta
spec:
  selector:
    matchLabels:
      app: resta
  template:
    metadata:
      labels:
        app: resta
    spec:
      containers:
        - name: resta
          image: resta:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
